name: test it

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: test it

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22]
        # supported Node.js release schedule: https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
